/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ats.global.techsoft.slayers.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employees service. Represents a row in the &quot;ATS_Employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ats.global.techsoft.slayers.model.impl.EmployeesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ats.global.techsoft.slayers.model.impl.EmployeesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employees
 * @generated
 */
@ProviderType
public interface EmployeesModel
	extends BaseModel<Employees>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employees model instance should use the {@link Employees} interface instead.
	 */

	/**
	 * Returns the primary key of this employees.
	 *
	 * @return the primary key of this employees
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employees.
	 *
	 * @param primaryKey the primary key of this employees
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employees.
	 *
	 * @return the uuid of this employees
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employees.
	 *
	 * @param uuid the uuid of this employees
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this employees.
	 *
	 * @return the employee ID of this employees
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employees.
	 *
	 * @param EmployeeId the employee ID of this employees
	 */
	public void setEmployeeId(long EmployeeId);

	/**
	 * Returns the group ID of this employees.
	 *
	 * @return the group ID of this employees
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employees.
	 *
	 * @param groupId the group ID of this employees
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employees.
	 *
	 * @return the company ID of this employees
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employees.
	 *
	 * @param companyId the company ID of this employees
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the emp key of this employees.
	 *
	 * @return the emp key of this employees
	 */
	public long getEmpKey();

	/**
	 * Sets the emp key of this employees.
	 *
	 * @param EmpKey the emp key of this employees
	 */
	public void setEmpKey(long EmpKey);

	/**
	 * Returns the emp name of this employees.
	 *
	 * @return the emp name of this employees
	 */
	@AutoEscape
	public String getEmpName();

	/**
	 * Sets the emp name of this employees.
	 *
	 * @param EmpName the emp name of this employees
	 */
	public void setEmpName(String EmpName);

	/**
	 * Returns the create date of this employees.
	 *
	 * @return the create date of this employees
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employees.
	 *
	 * @param createDate the create date of this employees
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employees.
	 *
	 * @return the modified date of this employees
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employees.
	 *
	 * @param modifiedDate the modified date of this employees
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the emp photo of this employees.
	 *
	 * @return the emp photo of this employees
	 */
	@AutoEscape
	public String getEmpPhoto();

	/**
	 * Sets the emp photo of this employees.
	 *
	 * @param EmpPhoto the emp photo of this employees
	 */
	public void setEmpPhoto(String EmpPhoto);

	/**
	 * Returns the emp gender of this employees.
	 *
	 * @return the emp gender of this employees
	 */
	@AutoEscape
	public String getEmpGender();

	/**
	 * Sets the emp gender of this employees.
	 *
	 * @param EmpGender the emp gender of this employees
	 */
	public void setEmpGender(String EmpGender);

	/**
	 * Returns the emp age of this employees.
	 *
	 * @return the emp age of this employees
	 */
	public int getEmpAge();

	/**
	 * Sets the emp age of this employees.
	 *
	 * @param EmpAge the emp age of this employees
	 */
	public void setEmpAge(int EmpAge);

	/**
	 * Returns the empl role of this employees.
	 *
	 * @return the empl role of this employees
	 */
	@AutoEscape
	public String getEmplRole();

	/**
	 * Sets the empl role of this employees.
	 *
	 * @param EmplRole the empl role of this employees
	 */
	public void setEmplRole(String EmplRole);

	/**
	 * Returns the emp address of this employees.
	 *
	 * @return the emp address of this employees
	 */
	@AutoEscape
	public String getEmpAddress();

	/**
	 * Sets the emp address of this employees.
	 *
	 * @param EmpAddress the emp address of this employees
	 */
	public void setEmpAddress(String EmpAddress);

	@Override
	public Employees cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}